### ISSUE TITLE
Import/Mapping a site with existing symlinks blows things up

### ISSUE THREAD

**Issue by JiveDig** [getflywheel/local-addon-volumes#6]
It took me a while to figure this out, but I found the culprit (I think).  I've been moving a few sites from DesktopServer to Local via BackupBuddy (in DS) then dragging into Local to import. The import appears to go smoothly, but after trying to map some repos (theme and plugins) I get a 404 for the new site, and there didn't appear to be a way to get it back. 

In order to get it to work properly I had to follow these steps.

1. Import into Local
2. Manually delete all symlinked directories
3. Add local directories via this add-on
4. Remap

I was just about to bail and go back to DS for this, but then I got it working by removing the symlinked directories. Maybe this will help someone else, or at least have a note somewhere that importing a site with symlinks will cause errors?

**Comment by jdgtl** [comment]
@JiveDig, I've had my uploads folder symlinked to an external in order to not fill up my local hard drive. But, now in local that symlink obviously doesn't work.

I've removed the symlink, and added the new maps via what you mentioned above. Still getting 403 errors on all images.

Do you, or anyone else, know if you can actually map the uploads folder outside the virtual box?

**Comment by claygriffiths** [comment]
@jrglass,

Do you have Faster Docker Volumes enabled? If so, after making the map you can try going to Help » Restart Local's Machine.
